version: '3.8'

services: 

  mongodb: 
    image: mongo:4.4.6
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "$MONGODB_PORT:$MONGODB_PORT"
    networks: 
      - mern

  express-app: 
    build: ./express-app
    container_name: express-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "$NODE_PORT:$NODE_PORT"
    depends_on:
      - mongodb
    environment: 
      - DB_HOST=mongodb
      - DB_PORT=$MONGODB_PORT
      - DB_NAME=$MONGODB_DATABASE
      - REACT_APP=$REACT_APP
    networks: 
      - mern

  react-app: 
    build: ./react-app
    container_name: react-app
    restart: unless-stopped
    ports:
      - "$REACT_PORT:$REACT_PORT"
    depends_on: 
      - express-app
    networks: 
      - mern

networks: 
  mern:
    driver: bridge